---
deployment:
  tasks:
    - export STATICPATH=/home/user/public_html/
    - export NODEPATH=/home/user/blognodeapp/
    
    # Static files
    - /bin/cp -R public_html/* $STATICPATH
    - /bin/cp -R public_html/public $STATICPATH
    
    # Node.js app
    - /bin/cp -R blognodeapp/* $NODEPATH
    - cd $NODEPATH
    - /bin/npm install --production
    - /bin/npm audit fix --production
    - /bin/pm2 delete scottishinsults || true
    - /bin/pm2 start app.js --name scottishinsults --time
    - /bin/pm2 save
    
    # Set permissions for static files
    - /bin/chmod 755 $STATICPATH
    - /bin/chmod 644 $STATICPATH/.htaccess
    - /bin/chmod 644 $STATICPATH/*.html
    - /bin/chmod 644 $STATICPATH/robots.txt
    - /bin/chmod 644 $STATICPATH/sitemap.xml
    - /bin/chmod 644 $STATICPATH/ads.txt
    - /bin/chmod 644 $STATICPATH/site.webmanifest
    - /bin/chmod 644 $STATICPATH/favicon.ico
    - /bin/chmod -R 755 $STATICPATH/public
    - /bin/chmod -R 755 $STATICPATH/.well-known
    - /bin/chmod -R 755 $STATICPATH/nc_assets
    
    # Set permissions for Node.js app
    - /bin/chmod 755 $NODEPATH
    - /bin/chmod 644 $NODEPATH/.htaccess
    - /bin/chmod 755 $NODEPATH/app.js
    - /bin/chmod 755 $NODEPATH/blog-engine.js
    - /bin/chmod -R 755 $NODEPATH/views
    - /bin/chmod -R 755 $NODEPATH/private
    - /bin/chmod -R 755 $NODEPATH/data
    - /bin/chmod -R 755 $NODEPATH/scripts
    - /bin/chmod 600 $NODEPATH/.env
    
    # Create logs directory
    - /bin/mkdir -p $NODEPATH/logs
    - /bin/chmod 755 $NODEPATH/logs
    
    # Backup database
    - /bin/mysqldump -u $DB_USER -p$DB_PASSWORD $DB_NAME > $NODEPATH/backups/db_$(date +%Y%m%d_%H%M%S).sql
    
    # Log deployment
    - /bin/echo "Deployment completed at $(date)" >> $NODEPATH/logs/deployment.log 